controller_server:
  ros__parameters:
    controller_frequency: 20.0
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]
    
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: True

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      max_vel_x: 0.26
      max_vel_theta: 1.82
      min_speed_xy: 0.0
      max_speed_xy: 0.26
      critics: ["GoalDist", "ObstacleFootprint", "Twirling", "PathAlign", "PathDist"]
      
      GoalDist:
        critic_name: "GoalDistCritic"
        scale: 24.0

      ObstacleFootprint:
        critic_name: "ObstacleFootprintCritic"
        scale: 32.0
        safety_dist: 0.1
        inflation_dist: 0.6

      Twirling:
        critic_name: "TwirlingCritic"
        scale: 32.0
        enabled: true

      PathAlign:
        critic_name: "PathAlignCritic"
        scale: 32.0
        forward_point_distance: 0.325

      PathDist:
        critic_name: "PathDistCritic"
        scale: 32.0




# controller_server:
#   ros__parameters:
#     controller_frequency: 20.0
#     min_x_velocity_threshold: 0.001
#     min_theta_velocity_threshold: 0.001
#     odom_topic: "odom"
#     controller_plugins: ["FollowPath"]
#     progress_checker_plugins: ["progress_checker"]
#     goal_checker_plugins: ["goal_checker"]
#     progress_checker:
#       plugin: "nav2_controller::SimpleProgressChecker"
#       required_movement_radius: 0.5
#       movement_time_allowance: 10.0
#     goal_checker:
#       plugin: "nav2_controller::SimpleGoalChecker"
#       xy_goal_tolerance: 0.25
#       yaw_goal_tolerance: 0.25
#       stateful: True
#     FollowPath:
#       plugin: "dwb_core::DWBLocalPlanner"

