map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "/home/beto/ackbot_ws/src/ackbot_nav2_bringup/maps/map.yaml"
    frame_id: map
    resolution: 0.05
    origin: [0.0, 0.0, 0.0]
    free_thresh: 0.25
    occupied_thresh: 0.65